In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
cafe_p = pd.read_csv('/home/panda2bat/Avivorous_bat/output/13_evolution-family_analysis/CAFE2/double/Base_branch_probabilities.tab', sep = '\t')
cafe_c = pd.read_csv('/home/panda2bat/Avivorous_bat/output/13_evolution-family_analysis/CAFE2/double/Base_change.tab', sep = '\t')
cafe_n = pd.read_csv('/home/panda2bat/Avivorous_bat/output/13_evolution-family_analysis/CAFE2/double/Base_count.tab', sep = '\t')

In [3]:
def change_columns(df):
    columns_lst = list()
    for i in df.columns:
        i = re.sub(r'[#<>]', '', i)
        if i == 'FamilyID':
            i = i
        else:
            if not i.isdigit():
                i = re.sub(r'[0-9]*', '', i)
            else:
                i = 'n_' + i
        columns_lst.append(i)
    df.columns = columns_lst
    return(df)

In [4]:
cafe_p = change_columns(cafe_p)
cafe_c = change_columns(cafe_c)
cafe_n = change_columns(cafe_n)

In [33]:
def parse_species(species, cafe_p, cafe_c, cafe_n):
    sig = cafe_p[cafe_p.loc[:, species] < 0.01].loc[:, ['FamilyID', species]]
    cha = cafe_c[cafe_c.FamilyID.isin(sig.FamilyID)].loc[:, ['FamilyID', species]]
    num = cafe_n[cafe_n.FamilyID.isin(sig.FamilyID)].loc[:, ['FamilyID', species]]
    merge = pd.merge(sig, cha, on = 'FamilyID', how = 'left', suffixes=['_p', '_c'])
    merge = pd.merge(merge, num, on = 'FamilyID', how = 'left')
    merge = merge.rename(columns = {species:f'{species}_n'})
    increase = len(cha[cha.loc[:, species] > 0])
    decrease = len(cha[cha.loc[:, species] < 0])
    return(increase, decrease, merge)

In [26]:
increase, decrease, num = parse_species('EptFus', cafe_p, cafe_c, cafe_n)

In [27]:
num[num.loc[:,'EptFus_n'] < 0]

Empty DataFrame
Columns: [FamilyID, EptFus_p, EptFus_c, EptFus_n]
Index: []

In [34]:
df_tmp = {'species':[],'increase':[], 'decrease':[], 'merge':[]}
for i in list(cafe_c.columns)[1:]:
    increase, decrease, merge = parse_species(i, cafe_p, cafe_c, cafe_n)
    df_tmp['species'].append(i)
    df_tmp['increase'].append(increase)
    df_tmp['decrease'].append(decrease)
    df_tmp['merge'].append(merge)
final = pd.DataFrame(df_tmp)

,species,increase,decrease,merge
0,EptFus,378,0,FamilyID EptFus_p EptFus_c Ep...
1,IaIo,303,139,FamilyID IaIo_p IaIo_c IaIo...
2,NycAvi,164,53,FamilyID NycAvi_p NycAvi_c Ny...
3,PipKuh,333,11,FamilyID PipKuh_p PipKuh_c Pi...
4,MyoBra,342,22,FamilyID MyoBra_p MyoBra_c My...
5,MyoLuc,386,9,FamilyID MyoLuc_p MyoLuc_c My...
6,MyoDav,182,48,FamilyID MyoDav_p MyoDav_c My...
7,MyoMyo,384,42,FamilyID MyoMyo_p MyoMyo_c My...
8,n_8,57,2,FamilyID n_8_p n_8_c n_8_n ...
9,n_9,35,8,FamilyID n_9_p n_9_c n_9_n ...
10,n_10,100,543,FamilyID n_10_p n_10_c n_10_n 0...
11,n_11,30,328,FamilyID n_11_p n_11_c n_11_n 0 ...
12,ArtJam,148,10,FamilyID ArtJam_p ArtJam_c Ar...
13,StuHon,148,35,FamilyID StuHon_p StuHon_c StuHon...
14,PhyDis,210,7,FamilyID PhyDis_p PhyDis_c Ph...
15,PhyHas,134,17,FamilyID PhyHas_p PhyHas_c Ph...
16,n_16,38,1,FamilyID n_16_p n_16_c n_16_n 0 ...
17,n_17,136,0,FamilyID n_17_p n_17_c n_17...
18,n_18,22,3,FamilyID n_18_p n_18_c n_18_...
19,n_19,95,1,FamilyID n_19_p n_19_c n_19_n 0 ...
20,PteGig,250,458,FamilyID PteGig_p PteGig_c Pt...
21,PteVam,225,625,FamilyID PteVam_p PteVam_c PteVam...
22,n_22,45,2,FamilyID n_22_p n_22_c n_22_...
23,MinNat,21,21,FamilyID MinNat_p MinNat_c Min...
24,n_24,57,0,FamilyID n_24_p n_24_c n_24_...
25,DesRot,96,9,FamilyID DesRot_p DesRot_c De...
26,n_26,64,168,FamilyID n_26_p n_26_c n_26_n 0...
27,PteAle,45,792,FamilyID PteAle_p PteAle_c PteAle...
28,n_28,20,0,FamilyID n_28_p n_28_c n_28_n 0 ...
29,MolMol,93,6,FamilyID MolMol_p MolMol_c Mol...
30,n_30,83,0,FamilyID n_30_p n_30_c n_30_...
31,PtePar,64,8,FamilyID PtePar_p PtePar_c Pte...
32,n_32,67,2,FamilyID n_32_p n_32_c n_32_n 0 ...
33,RouAeg,155,5,FamilyID RouAeg_p RouAeg_c RouAeg...
34,HipArm,32,11,FamilyID HipArm_p HipArm_c Hip...
35,RhiFer,110,2,FamilyID RhiFer_p RhiFer_c Rh...
36,n_36,57,1,FamilyID n_36_p n_36_c n_36_...
37,n_37,109,1,FamilyID n_37_p n_37_c n_37...
38,n_38,22,1,FamilyID n_38_p n_38_c n_38_...
39,n_39,11,4,FamilyID n_39_p n_39_c n_39_...
40,n_40,78,0,FamilyID n_40_p n_40_c n_40_...
41,n_41,26,0,FamilyID n_41_p n_41_c n_41_n 0 ...
42,n_42,0,0,"Empty DataFrame Columns: [n_42_p, n_42_c, Fami..."